alias _articles="cd /c/projects/articles"
alias _c="clear"
alias _bashrc="cd; vi .bashrc"
alias _bashrcreload="cd; source .bashrc"
alias la="ls -lat"
alias ll="ls -la"
alias _ga="git add .bashrc; git commit -m '%1'; git push"
